
            <!-- Main hero unit for a primary marketing message or call to action -->
		<div class="hero-unit">
		    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>
		    <p>Congratulations! You have successfully installed the <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF2 Skeleton Application</a> You are currently running Zend Framework version. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.</p>
		    <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/zf2" target="_blank">Fork Zend Framework 2 on GitHub &raquo;</a></p>
		</div>
		

      <!-- Example row of columns -->
  			 <div class="row-fluid"   >
			    <div class="span4 well" style=" color: white; background-color: #00bae4; ">
			        <h2>Follow Development</h2>
			        <p>Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 </p>
			        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank">ZF2 Development Portal &raquo;</a></p>
			    </div>
			
			    <div class="span4 well" style="color: white; background-color: #e21776; ">
			        <h2>Discover Modules</h2>
			        <p>The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.</p>
			        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank">Explore ZF2 Modules &raquo;</a></p>
			   </div>
			
			   <div class="span4 well" style="color: white; background-color: #ffb812;">
			       <h2>Help &amp; Support</h2>
			       <p>If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively</p>
			       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Ping us on IRC</a></p>
			   </div>
			</div>