<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Portal Distribuidor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
     <?php echo $this->headLink()->appendStylesheet('/css/bootstrap.css') ?>
     <?php echo $this->headLink()->appendStylesheet('/css/style.css') ?>
     <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <?php echo $this->headLink()->appendStylesheet('/css/bootstrap-responsive.css') ?>
  
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="/img/favicon.ico">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/index">Portal Distribuidor</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <!-- 
              <li><a href="/test">Home</a></li>
              <li><a href="/test">About</a></li>
              <li><a href="/test">test</a></li>
       			-->
            </ul>
   			
      
              <!--       <form class="navbar-form pull-right" action="/auth/login" method="post">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">  <button type="submit" class="btn">Sign in</button>
            </form>            
               -->
              
            <div class="links pull-right">
    		<a class="btn" href="/auth/login" title="Login">Login »</a>
             												 
					</div>
            
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
	<?php echo $this->layout()->content ?>
	  <hr>

      <footer>
           <p class="pull-right"><a href="#">Volver arriba</a></p>
                <p>&copy; 2012 - 2013 by Solución Integral de Facturación Electrónica e Informática Sifei S.A de C.V. All rights reserved.</p>
                
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap-transition.js"></script>
    <script src="/js/bootstrap-alert.js"></script>
    <script src="/js/bootstrap-modal.js"></script>
    <script src="/js/bootstrap-dropdown.js"></script>
    <script src="/js/bootstrap-scrollspy.js"></script>
    <script src="/js/bootstrap-tab.js"></script>
    <script src="/js/bootstrap-tooltip.js"></script>
    <script src="/js/bootstrap-popover.js"></script>
    <script src="/js/bootstrap-button.js"></script>
    <script src="/js/bootstrap-collapse.js"></script>
    <script src="/js/bootstrap-carousel.js"></script>
    <script src="/js/bootstrap-typeahead.js"></script>

  </body>
</html>